name: pro_health
description: A cross-platform complete healthcare solutions.

version: 0.8.57+6

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  agora_rtc_engine: ^4.0.7
  animated_splash_screen: ^1.1.0
  auto_animated: ^3.0.0
  cached_network_image: ^3.1.0
  card_swiper: ^1.0.4
  chart_sparkline: ^1.0.5
  collection: ^1.15.0-nullsafety.4
  convex_bottom_bar: ^3.0.0
  cloud_firestore: ^2.5.3
  cupertino_icons: ^1.0.3
  datetime_picker_formfield: ^2.0.0
  dropdown_button2: ^1.0.7
  double_back_to_close_app: ^2.1.0
  dio: ^4.0.0
  dotted_line: ^3.0.0
  dropdown_search: ^0.6.3
  expansion_tile_card: ^2.0.0
  find_dropdown: ^1.0.0
  firebase_auth: ^3.1.1
  firebase_core: ^1.6.0
  firebase_storage: ^10.0.3
  flutter_firebase_chat_core: ^1.4.2
  flare_flutter: ^3.0.2
  flutter:
    sdk: flutter
  flutter_datetime_picker: ^1.5.1

  # flutter_html_to_pdf: ^0.6.1
  flutter_launcher_icons: ^0.9.2
  flutter_rating_stars: ^1.0.3+4
  flutter_screenutil: ^5.0.0+2
  flutter_spinkit: ^5.1.0
  flutter_staggered_animations: ^1.0.0
  flutter_staggered_grid_view: ^0.4.0
  flutter_switch: ^0.3.2
  flutter_typeahead: ^3.2.1
  flutter_email_sender: ^5.0.2
 
  font_awesome_flutter: ^9.1.0
  form_field_validator: ^1.1.0
  jitsi_meet: ^4.0.0

  get: ^4.3.8
  group_radio_button: ^1.1.0
  http: ^0.13.3
  icon_badge: ^1.0.0
  image_picker: ^0.8.4
  intl: ^0.17.0
  marquee: ^2.2.0
  mailer: ^5.0.2
  multi_image_picker: ^4.8.01
  nanoid: ^1.0.0
  oktoast: ^3.1.1
  open_file: ^3.2.1
  page_transition: ^2.0.1-nullsafety.0
  path: ^1.8.0
  path_provider: ^2.0.2
  pdf: ^3.5.0
  percent_indicator: ^3.0.1
  permission_handler: ^8.3.0
  printing: ^5.6.0
  rflutter_alert: ^2.0.4
  rxdart: ^0.26.0
  select_form_field: ^2.2.0
  share: ^2.0.4
  shared_preferences: ^2.0.7
  simple_autocomplete_formfield: ^0.3.0
  syncfusion_flutter_pdfviewer: ^19.2.59-beta
  syncfusion_flutter_pdf: ^19.2.60-beta
  syncfusion_flutter_barcodes: ^19.2.60
  transparent_image: ^2.0.0
  uuid: ^3.0.4
  weekday_selector: ^1.0.0

dev_dependencies:
  flutter_native_splash: ^1.2.1
  flutter_test:
    sdk: flutter

flutter_native_splash:

  # This package generates native code to customize Flutter's default white native splash screen
  # with background color and splash image.
  # Customize the parameters below, and run the following command in the terminal:
  # flutter pub run flutter_native_splash:create
  # To restore Flutter's default white splash screen, run the following command in the terminal:
  # flutter pub run flutter_native_splash:remove
  # color or background_image is the only required parameter.  Use color to set the background
  # of your splash screen to a solid color.  Use background_image to set the background of your
  # splash screen to a png image.  This is useful for gradients. The image will be stretch to the
  # size of the app. Only one parameter can be used, color and background_image cannot both be set.
  color: "#FFFFFF"
  #background_image: "assets/background.png"
  # Optional parameters are listed below.  To enable a parameter, uncomment the line by removing 
  # the leading # character.
  # The image parameter allows you to specify an image used in the splash screen.  It must be a 
  # png file and should be sized for 4x pixel density.
  image: assets/splash-logo.png

  # The color_dark, background_image_dark, and image_dark are parameters that set the background
  # and image when the device is in dark mode. If they are not specified, the app will use the
  # parameters from above. If the image_dark parameter is specified, color_dark or 
  # background_image_dark must be specified.  color_dark and background_image_dark cannot both be
  # set.
  #color_dark: "#042a49"
  #background_image_dark: "assets/dark-background.png"
  #image_dark: assets/splash-invert.png
  # The android, ios and web parameters can be used to disable generating a splash screen on a given 
  # platform.
  android: true
  ios: true
  web: true

  # The position of the splash image can be set with android_gravity, ios_content_mode, and
  # web_image_mode parameters.  All default to center.
  #
  # android_gravity can be one of the following Android Gravity (see 
  # https://developer.android.com/reference/android/view/Gravity): bottom, center, 
  # center_horizontal, center_vertical, clip_horizontal, clip_vertical, end, fill, fill_horizontal,
  # fill_vertical, left, right, start, or top.
  android_gravity: center
  # ios_content_mode can be one of the following iOS UIView.ContentMode (see 
  # https://developer.apple.com/documentation/uikit/uiview/contentmode): scaleToFill, 
  # scaleAspectFit, scaleAspectFill, center, top, bottom, left, right, topLeft, topRight, 
  # bottomLeft, or bottomRight.
  ios_content_mode: center
  # web_image_mode can be one of the following modes: center, contain, stretch, and cover.
  web_image_mode: center

  # To hide the notification bar, use the fullscreen parameter.  Has no affect in web since web 
  # has no notification bar.  Defaults to false.
  # NOTE: Unlike Android, iOS will not automatically show the notification bar when the app loads.
  #       To show the notification bar, add the following code to your Flutter app:
  #       WidgetsFlutterBinding.ensureInitialized();
  #       SystemChrome.setEnabledSystemUIOverlays([SystemUiOverlay.bottom, SystemUiOverlay.top]);
  fullscreen: true
  # If you have changed the name(s) of your info.plist file(s), you can specify the filename(s) 
  # with the info_plist_files parameter.  Remove only the # characters in the three lines below,
  # do not remove any spaces:
  #info_plist_files:
  #  - 'ios/Runner/Info-Debug.plist'
  #  - 'ios/Runner/Info-Release.plist'
  # To enable support for Android 12, set the following parameter to true.  Defaults to false.
  #android12: true

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/logo.png
    - assets/prohealthhlogo.png
    - assets/doctorsignin.png
    - assets/patientsignin.png
    - assets/pharmalogo.png
    - assets/doctorimg.png
    - assets/apatient.png
    - assets/icons/doctor/
    - assets/icons/patient/
    - assets/splash-logo.png
    - assets/default.jpg
    - assets/patient.png

  fonts:
    - family: Segoe
      fonts:
        - asset: assets/fonts/Segoeuil.ttf
          weight: 500
    - family: Nunito
      fonts:
        - asset: assets/fonts/Nunito.ttf
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 600
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700
    - family: Poppins-Bold
      fonts:
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700

    - family: Poppins-Medium
      fonts:
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 600

    - family: SolaimanLipi
      fonts:
        - asset: assets/fonts/SolaimanLipi.ttf
          weight: 600

    - family: Shonar-Bangla
      fonts:
        - asset: assets/fonts/Shonar.ttf
          weight: 600
        - asset: assets/fonts/Shonarb.ttf
          weight: 700

    - family: Kalpurush
      fonts:
        - asset: assets/fonts/kalpurush.ttf
          weight: 600
       

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/logo.png"

flutter_launcher_name:
  name: "ProHealth"
